project_id = "msujaimgdxhxmtlaabvn"

[functions.admin-auth]
verify_jwt = false

[functions.admin-management]
verify_jwt = false

[functions.contact-submit]
verify_jwt = false

[functions.csv-upload]
verify_jwt = false