project_id = "msujaimgdxhxmtlaabvn"

[functions.admin-auth]
verify_jwt = false

[functions.admin-management]
verify_jwt = false

[functions.contact-submit]
verify_jwt = false

[functions.csv-upload]
verify_jwt = false

[functions.backup-system]
verify_jwt = false

[functions.send-application-notification]
verify_jwt = false

[functions.export-data]
verify_jwt = false

[functions.full-backup]
verify_jwt = false

[functions.leads-export-with-documents]
verify_jwt = false

[functions.leads-import-with-documents]
verify_jwt = false